meta:
  id: process-optimization.dev
log:
  level: INFO
app:
  mode: hybrid  # continuous, api, hybrid
api:
  host: 0.0.0.0
  port: 8005  # Changed to avoid conflicts
  debug: true

database:
  host: localhost
  port: 5432  # Development port
  dbname: process_db
  user: postgres
  password: password
storage:
  minio:
    endpoint: localhost:9002  # Development port
    access_key: user
    secret_key: password
    bucket: process-optimization
optimization:
  interval_seconds: 300
  max_iterations: 1000
  tolerance: 1e-6
  config_file: process-optimization-strategy-config.yaml
