meta:
  id: process-optimization.dev
log:
  level: DEBUG
app:
  mode: hybrid  # continuous, api, hybrid
api:
  host: 0.0.0.0
  port: 5002  # Changed to avoid conflicts
  debug: true
redis:
  host: localhost
  port: 6380  # Development port
database:
  host: 65.1.237.188
  port: 5433  # Development port
  dbname: process_db
  user: postgres
  password: Uptime@975
storage:
  minio:
    endpoint: localhost:9002  # Development port
    access_key: user
    secret_key: password
    bucket: process-optimization
optimization:
  interval_seconds: 300
  max_iterations: 1000
  tolerance: 1e-6
  config_file: process-optimization-strategy-config.yaml
