services:
  minio:
    image: minio/minio:latest
    container_name: minio-server
    ports:
      - "9090:9000"
      - "9091:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9091
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - minio_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MinIO client for initial setup
  minio-client:
    image: minio/mc:latest
    container_name: minio-client
    depends_on:
      - minio
    networks:
      - minio_network
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb myminio/process-optimization --ignore-existing;
      /usr/bin/mc policy set public myminio/process-optimization;
      echo 'MinIO setup completed';
      tail -f /dev/null
      "

volumes:
  minio_data:
    driver: local

networks:
  minio_network:
    driver: bridge
