constraint_limits:
  Burning_zone_temperature:
    op_max: 1000.0
    op_min: 0.0
    var_max: 1000.0
    var_min: 0.0
display_variables:
- Secondary_Air_Temperature
- Calciner_temperature_PV
- PH_Fan_Speed_PV
- combined_Feed_rate
- Kiln_Coal_PV
input_values:
  Burning_zone_temperature: 0.0
  Calciner_temperature_PV: 900.0
  Cooler_Fan_3_Flow: 50000.0
  Cooler_Fan_4_Flow: 58000.0
  Cooler_Fan_5_Flow: 38000.0
  Cooler_Fan_6_Flow: 43000.0
  Cooler_Fan_7_Flow: 37000.0
  Cooler_Fan_8_Flow: 47000.0
  Cooler_Fan_9_Flow: 62000.0
  Kiln_Coal_PV: 6.56
  Kiln_Feed_SFF_1_Feed_rate: 245.0
  Kiln_Feed_SFF_2_Feed_rate: 0.0
  PH_Fan_Speed_PV: 700.0
  Secondary_Air_Temperature: 0.0
skills:
  cs_kpi_calculation_flow:
    class: CompositionSkill
    config:
      skill_sequence:
      - mf_calc_delta_Secondary_Air_Temperature
      - mf_calc_delta_Calciner_temperature_PV
      - mf_calc_delta_PH_Fan_Speed_PV
      - mf_calc_delta_combined_Feed_rate
      - mf_calc_delta_Kiln_Coal_PV
      - im_predict_delta_Burning_zone_temperature
      - mf_calc_predicted_Burning_zone_temperature
      - mf_intervention_penalty_coal
      - mf_cost_function
    inputs:
    - PH_Fan_Speed_PV
    - combined_Feed_rate
    - Kiln_Coal_PV
    - Secondary_Air_Temperature
    - Calciner_temperature_PV
    outputs:
    - cost_function_total
  im_predict_delta_Burning_zone_temperature:
    class: InferenceModel
    config:
      feature_engineering:
        feature_engineering_timestamp: '2025-09-02 07:46:01.791408'
        lag_method: custom
        lag_offset:
          Calciner_temperature_PV:
            lag: 9
            offset: 29
            variation: Absolute
          Kiln_Coal_PV:
            lag: 26
            offset: 59
            variation: Increment
          PH_Fan_Speed_PV:
            lag: 1
            offset: 5
            variation: Absolute
          Secondary_Air_Temperature:
            lag: 1
            offset: 25
            variation: Increment
          combined_Feed_rate:
            lag: 25
            offset: 38
            variation: Increment
        smoothing:
          alpha: null
          method: mean
      metadata_path: models/Burning_zone_temperature_MODEL_INFO_mean_MinMax/Burning_zone_temperature_metadata.json
      model_path: models/Burning_zone_temperature_MODEL_INFO_mean_MinMax/Burning_zone_temperature_model.pth
      model_type: ANN
      scaler_path: models/Burning_zone_temperature_MODEL_INFO_mean_MinMax/Burning_zone_temperature_scalers.pkl
    inputs:
    - delta_combined_Feed_rate
    - delta_Kiln_Coal_PV
    - Calciner_temperature_PV
    - delta_Secondary_Air_Temperature
    - PH_Fan_Speed_PV
    outputs:
    - delta_Burning_zone_temperature
  mf_calc_delta_Calciner_temperature_PV:
    class: MathFunction
    config:
      formula: Calciner_temperature_PV_dof
    inputs:
    - Calciner_temperature_PV
    outputs:
    - delta_Calciner_temperature_PV
  mf_calc_delta_Kiln_Coal_PV:
    class: MathFunction
    config:
      formula: Kiln_Coal_PV_dof - Kiln_Coal_PV_current
    inputs:
    - Kiln_Coal_PV
    outputs:
    - delta_Kiln_Coal_PV
  mf_calc_delta_PH_Fan_Speed_PV:
    class: MathFunction
    config:
      formula: PH_Fan_Speed_PV_dof
    inputs:
    - PH_Fan_Speed_PV
    outputs:
    - delta_PH_Fan_Speed_PV
  mf_calc_delta_Secondary_Air_Temperature:
    class: MathFunction
    config:
      formula: Secondary_Air_Temperature_dof - Secondary_Air_Temperature_current
    inputs:
    - Secondary_Air_Temperature
    outputs:
    - delta_Secondary_Air_Temperature
  mf_calc_delta_combined_Feed_rate:
    class: MathFunction
    config:
      formula: combined_Feed_rate_dof - combined_Feed_rate_current
    inputs:
    - combined_Feed_rate
    outputs:
    - delta_combined_Feed_rate
  mf_calc_predicted_Burning_zone_temperature:
    class: MathFunction
    config:
      formula: Burning_zone_temperature_current + delta_Burning_zone_temperature_dof
    inputs:
    - Burning_zone_temperature
    - delta_Burning_zone_temperature
    outputs:
    - predicted_Burning_zone_temperature
  mf_cost_function:
    class: MathFunction
    config:
      formula: ((cost_coal_weight * delta_Kiln_Coal_PV_dof / Kiln_Coal_PV_threshold)
        + (cost_feed_rate_weight * delta_combined_Feed_rate_dof / combined_Feed_rate_threshold)
        + penalty_coal_intervention_dof)
    inputs:
    - penalty_coal_intervention
    - delta_Kiln_Coal_PV
    - delta_combined_Feed_rate
    - Kiln_Coal_PV
    - combined_Feed_rate
    outputs:
    - cost_function_total
  mf_intervention_penalty_coal:
    class: MathFunction
    config:
      formula: penalty_weight * max(0, (delta_combined_Feed_rate_dof / combined_Feed_rate_threshold))
        * max(0, -(delta_Kiln_Coal_PV_dof / Kiln_Coal_PV_threshold))
    inputs:
    - delta_combined_Feed_rate
    - delta_Kiln_Coal_PV
    - combined_Feed_rate
    - Kiln_Coal_PV
    outputs:
    - penalty_coal_intervention
  mf_sum_combined_feed_rate:
    class: MathFunction
    config:
      dataframe_formula:
        axis: 1
        method: sum
      formula: Kiln_Feed_SFF_1_Feed_rate + Kiln_Feed_SFF_2_Feed_rate
    inputs:
    - Kiln_Feed_SFF_1_Feed_rate
    - Kiln_Feed_SFF_2_Feed_rate
    outputs:
    - combined_Feed_rate
  mf_sum_cooler_flows:
    class: MathFunction
    config:
      dataframe_formula:
        axis: 1
        method: sum
      formula: Cooler_Fan_3_Flow + Cooler_Fan_4_Flow + Cooler_Fan_5_Flow + Cooler_Fan_6_Flow
    inputs:
    - Cooler_Fan_3_Flow
    - Cooler_Fan_4_Flow
    - Cooler_Fan_5_Flow
    - Cooler_Fan_6_Flow
    outputs:
    - Cooler_Fan_3_4_5_6_Flow
  mf_sum_cooler_flows_2:
    class: MathFunction
    config:
      dataframe_formula:
        axis: 1
        method: sum
      formula: Cooler_Fan_7_Flow + Cooler_Fan_8_Flow + Cooler_Fan_9_Flow
    inputs:
    - Cooler_Fan_7_Flow
    - Cooler_Fan_8_Flow
    - Cooler_Fan_9_Flow
    outputs:
    - Cooler_Fan_7_8_9_Flow
  mf_sum_cooler_flows_3:
    class: MathFunction
    config:
      dataframe_formula:
        axis: 1
        method: sum
      formula: Cooler_Fan_4_Flow + Cooler_Fan_5_Flow + Cooler_Fan_6_Flow
    inputs:
    - Cooler_Fan_4_Flow
    - Cooler_Fan_5_Flow
    - Cooler_Fan_6_Flow
    outputs:
    - Cooler_Fan_4_5_6_Flow
  os_build_bounds:
    class: Bounds
    config: {}
    inputs: &id001
    - Secondary_Air_Temperature
    - combined_Feed_rate
    - PH_Fan_Speed_PV
    - Kiln_Coal_PV
    outputs: *id001
  os_build_constraints:
    class: Constraints
    config:
      template:
      - op_max: 1000.0
        op_min: 0.0
        predicted_var: predicted_Burning_zone_temperature
  os_main_optimizer:
    class: OptimizationSkill
    config:
      algorithm: SLSQP
      cost_feature_name: cost_function_total
      cost_skill_name: cs_kpi_calculation_flow
    inputs: *id001
    outputs: *id001
tasks:
- name: PreCalculateVariables
  skill_sequence:
  - mf_sum_cooler_flows
  - mf_sum_cooler_flows_2
  - mf_sum_cooler_flows_3
  - mf_sum_combined_feed_rate
- name: CalculateRecommendations
  skill_sequence:
  - os_build_bounds
  - os_build_constraints
  - os_main_optimizer
variables:
  Burning_zone_temperature:
    threshold: 1.0
    type: Informative
    units: ''
  Calciner_temperature_PV:
    type: Informative
    units: "\xB0C"
  Cooler_Fan_3_4_5_6_Flow:
    max_hard_limit: 300000.0
    min_hard_limit: 100000.0
    threshold: 2000.0
    type: Calculated
    units: m3/h
  Cooler_Fan_3_Flow:
    threshold: 2000.0
    type: Informative
    units: m3/h
  Cooler_Fan_4_5_6_Flow:
    max_hard_limit: 200000.0
    min_hard_limit: 100000.0
    threshold: 2000.0
    type: Calculated
    units: m3/h
  Cooler_Fan_4_Flow:
    threshold: 2000.0
    type: Informative
    units: m3/h
  Cooler_Fan_5_Flow:
    threshold: 2000.0
    type: Informative
    units: m3/h
  Cooler_Fan_6_Flow:
    threshold: 2000.0
    type: Informative
    units: m3/h
  Cooler_Fan_7_8_9_Flow:
    max_hard_limit: 200000.0
    min_hard_limit: 25000.0
    threshold: 1500.0
    type: Calculated
    units: m3/h
  Cooler_Fan_7_Flow:
    threshold: 1500.0
    type: Informative
    units: m3/h
  Cooler_Fan_8_Flow:
    threshold: 1500.0
    type: Informative
    units: m3/h
  Cooler_Fan_9_Flow:
    threshold: 1500.0
    type: Informative
    units: m3/h
  Kiln_Coal_PV:
    max_hard_limit: 16.0
    min_hard_limit: 8.0
    threshold: 0.05
    type: Operative
    units: t/h
  Kiln_Feed_SFF_1_Feed_rate:
    threshold: 5.0
    type: Informative
    units: t/h
  Kiln_Feed_SFF_2_Feed_rate:
    threshold: 1.0
    type: Informative
    units: t/h
  PH_Fan_Speed_PV:
    max_hard_limit: 1400.0
    min_hard_limit: 500.0
    threshold: 1.0
    type: Operative
    units: RPM
  Secondary_Air_Temperature:
    max_hard_limit: 1000.0
    min_hard_limit: 0.0
    threshold: 1.0
    type: Operative
    units: ''
  combined_Feed_rate:
    max_hard_limit: 400.0
    min_hard_limit: 100.0
    threshold: 2.0
    type: Calculated
    units: t/h
  cost_function_total:
    type: CalculatedKPI
    units: '-'
  delta_Burning_zone_temperature:
    type: Delta
    units: ''
  delta_Calciner_temperature_PV:
    type: Delta
    units: "\xB0C"
  delta_Cooler_Fan_3_4_5_6_Flow:
    type: Delta
    units: m3/h
  delta_Cooler_Fan_4_5_6_Flow:
    type: Delta
    units: m3/h
  delta_Cooler_Fan_7_8_9_Flow:
    type: Delta
    units: m3/h
  delta_Kiln_Coal_PV:
    type: Delta
    units: t/h
  delta_PH_Fan_Speed_PV:
    type: Delta
    units: RPM
  delta_Secondary_Air_Temperature:
    type: Delta
    units: ''
  delta_combined_Feed_rate:
    type: Delta
    units: t/h
  penalty_coal_intervention:
    type: CalculatedKPI
    units: '-'
  predicted_Burning_zone_temperature:
    type: Predicted
    units: ''
weights:
  cost_coal_weight: 1.0
  cost_feed_rate_weight: -1.0
  penalty_weight: 100.0
